# Generated by Django 2.2.13 on 2020-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200809_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues_types', to='webapp.Type', verbose_name='Type'),
        ),
    ]
